config/routes.rb
Rails.application.routes.draw do
  resources :dashboards, only: :index

  root to: 'dashboards#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/dashboards_controller.rb
class DashboardsController < ApplicationController
  def index
    expires_in 1.hour

    @currency_quotations = CurrencyQuotationsFinder.call

    respond_to do |format|
      format.html
      format.json { render json: @currency_quotations }
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/dashboards/index.html.erb
<div class='align-center'>
  <h3> Cotação do dólar últimos 7 dias </h3>

  <div id='quotations-chart'></div>

  <%= link_to 'Cotação do Real', dashboards_path, class: 'button', id: 'target-brl-button', remote: true %>
  <%= link_to 'Cotação do Euro', dashboards_path, class: 'button', id: 'target-eur-button', remote: true %>
  <%= link_to 'Cotação do Peso Argentino', dashboards_path, class: 'button', id: 'target-ars-button', remote: true %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>InnventRealQuotation</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>